name: Deploy App to Azure App Services

on:
  push:
    branches: [ "main" ]  # Trigger on push events to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu | Default operating system environment for workflows unless explicitly specified.
    steps:
    - name: Checkout code  # Step to check out the code from the repository | Fetch the source code repository into the runner machine where our workflow is executing.
      uses: actions/checkout@v4
    - name: Set up JDK 17 # Step to set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven # Step to build the project with Maven
      run: mvn clean install -DskipTests
    - name: Upload Artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: GitHubActionDemo
        path: ${{github.workspace}}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: GitHubActionDemo
      - name: Deploy code to Azure App Service
        uses: azure/webapps-deploy@v4
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v4

      - name: Log in to Azure
        uses: azure/login@v4
        with:
          app-name: GitHubActionDemoAppl
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
